
import click 
from main import run
@click.command()
@click.option('--input_dir', '-id', help='Sequence alignment map files folder(s) generated by alignment', type=click.Path(exists=True), multiple=True)
@click.option('--out_dir', '-o', default=os.getcwd(), type=click.Path(exists=True), help='Where to output the files')
@click.option('--samples', '-s', type=click.Path(exists=True), help='Path to the samples.csv file', default=None)
@click.option('--clusters', '-cl', type=click.Path(exists=True), help='Path to the clustering.json file', default=None)
@click.option('--library', '-l', type=click.Path(exists=True), help='Path to the library.csv file', default=None)
@click.option('--rnastructure_path', '-rs', type=click.Path(exists=True), help='Path to RNAstructure, to predict structure and free energy', default=None)
@click.option('--rnastructure_temperature', '-rst', type=bool, help='Use sample.csv temperature values for RNAstructure', default=False)
@click.option('--rnastructure_fold_args', '-rsa', type=str, help='Arguments to pass to RNAstructure fold', default=None)
@click.option('--rnastructure_dms', '-rsd', type=bool, help='Use the DMS signal to make predictions with RNAstructure', default=False)
@click.option('--rnastructure_dms_min_unpaired_value', '-rsdmin', type=int, help='Minimum unpaired value for using the dms signal as an input for RNAstructure', default=0.01)
@click.option('--rnastructure_dms_max_paired_value', '-rsdmax', type=int, help='Maximum paired value for using the dms signal as an input for RNAstructure', default=0.05)
@click.option('--rnastructure_partition', '-rspa', type=bool, help='Use RNAstructure partition function to predict free energy', default=False)
@click.option('--rnastructure_probability', '-rspr', type=bool, help='Use RNAstructure partition function to predict per-base mutation probability', default=False)
@click.option('--poisson', '-po', type=bool, help='Predict Poisson confidence intervals', default=True)

def cli(**args):
    run(**args)

if __name__ == '__main__':
    run()
