name: "Tests"

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update apt-get and install dependencies
      run: |
        sudo apt-get update

    - name: install apt-get dependencies
      run: |
        sudo apt-get install -y libzbar-dev
        sudo apt-get install unzip

    - name: Install Python 3.10
      run: |
        conda install python=3.10

    - name: Install Samtools
      run: 
        sudo apt-get install samtools
        samtools version

    - name: Install RNAstructure
      run: |
        unzip RNAstructureSource.zip 
        sudo apt-get update && sudo apt-get install make 
        cd RNAstructure 
        sudo apt-get update && sudo apt-get install -y apt-utils
        sudo apt-get install -y g++
        sudo apt-get install libsimde-dev
        make all
        DATAPATH="RNAstructure/data_tables/"
        PATH="$PATH:RNAstructure/exe/"
        export DATAPATH
        export PATH
        cd ..
        ls RNAstructure/data_tables
        ls RNAstructure/exe

    - name: Test RNAstructure
      run: |
        echo '>seq1\nGCGC' > test.fasta
        Fold test.fasta test.ct
        ct2dot test.ct 1 test.txt
        cat test.txt

        
    - name: Install Bowtie2
      run: |
        ZIP=bowtie2-2.4.5-source.zip
        URL=https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.4.5/bowtie2-2.4.5-source.zip/download/
        FOLDER=bowtie2-2.4.5-source
        SOURCE=bowtie2-2.4.5
        DST=deps
        BT2=$PATH:$DST/$FOLDER/
        mkdir $DST
        wget -q $URL -O $DST/$ZIP && \
        unzip $DST/$ZIP -d $DST && \
        rm $DST/$ZIP && \
        cd $DST/$SOURCE && \
        make
        PATH="$PATH:/deps/bowtie2-2.4.5"
        export PATH


    - name: Install Fastqc
      run: conda install -c bioconda fastqc

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Install DREEM
      run: |
        pip install .

    - name: Test DREEM
      run: |
        pytest -v

