name: "RNAstructure Test"

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  Run-RNAstructure: 
    runs-on: ubuntu-latest
    steps: 
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install RNAstructure
        run: |
          conda info
          conda list
          conda install -c bioconda rnastructure
      
      - name: Run RNAstructure
        run: |
          echo ">ref\nGGCGACACAGTCGACGGTTTTCACA">ref.fasta
          Fold ref.fasta ref.ct
          ct2dot ref.ct 1 ref.txt
          cat ref.txt